# Generated by Django 3.2.5 on 2021-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210727_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
